from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 888)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(-240, 0, 1601, 861))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Background.setFont(font)
        self.Background.setStyleSheet("background-color: #2C2F33 ;")
        self.Background.setText("")
        self.Background.setAlignment(QtCore.Qt.AlignCenter)
        self.Background.setObjectName("Background")
        self.Heading = QtWidgets.QLabel(self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(310, 0, 191, 81))
        self.Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.Heading.setObjectName("Heading")
        self.Fname = QtWidgets.QLabel(self.centralwidget)
        self.Fname.setGeometry(QtCore.QRect(0, 90, 161, 81))
        self.Fname.setAlignment(QtCore.Qt.AlignCenter)
        self.Fname.setObjectName("Fname")
        self.Lname = QtWidgets.QLabel(self.centralwidget)
        self.Lname.setGeometry(QtCore.QRect(0, 170, 161, 81))
        self.Lname.setAlignment(QtCore.Qt.AlignCenter)
        self.Lname.setObjectName("Lname")
        self.Email = QtWidgets.QLabel(self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(-40, 250, 191, 91))
        self.Email.setAlignment(QtCore.Qt.AlignCenter)
        self.Email.setObjectName("Email")
        self.txtfname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtfname.setGeometry(QtCore.QRect(230, 110, 371, 41))
        self.txtfname.setObjectName("txtfname")
        self.txtmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtmail.setGeometry(QtCore.QRect(230, 270, 371, 41))
        self.txtmail.setObjectName("txtmail")
        self.txtlname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtlname.setGeometry(QtCore.QRect(230, 190, 371, 41))
        self.txtlname.setObjectName("txtlname")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(240, 370, 501, 91))
        self.Photo.setStyleSheet("")
        self.Photo.setText("")
        self.Photo.setObjectName("Photo")
        self.Uploadbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Uploadbtn.setGeometry(QtCore.QRect(10, 370, 191, 91))
        self.Uploadbtn.setStyleSheet("font-color:rgb(255, 255, 255);\n"
"background-color: rgb(114, 137, 218);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.Uploadbtn.setObjectName("Uploadbtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 590, 591, 251))
        self.groupBox.setProperty("jnn", "")
        self.groupBox.setObjectName("groupBox")
        self.searchbtn = QtWidgets.QPushButton(self.groupBox)
        self.searchbtn.setGeometry(QtCore.QRect(40, 50, 111, 41))
        self.searchbtn.setStyleSheet("background-color: rgb(114, 136, 217);")
        self.searchbtn.setObjectName("searchbtn")
        self.txtsearch = QtWidgets.QLineEdit(self.groupBox)
        self.txtsearch.setGeometry(QtCore.QRect(170, 50, 371, 41))
        self.txtsearch.setText("")
        self.txtsearch.setObjectName("txtsearch")
        self.tbresult = QtWidgets.QTableWidget(self.groupBox)
        self.tbresult.setGeometry(QtCore.QRect(40, 100, 501, 141))
        self.tbresult.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.tbresult.setColumnCount(8)
        self.tbresult.setObjectName("tbresult")
        self.tbresult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbresult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbresult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbresult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbresult.setHorizontalHeaderItem(3, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 500, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(114, 135, 216);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Heading.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#ffffff;\">FORM 1</span></p></body></html>"))
        self.Fname.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#ffffff;\">First Name</span></p></body></html>"))
        self.Lname.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#ffffff;\">Last Name</span></p></body></html>"))
        self.Email.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#ffffff;\">Email</span></p></body></html>"))
        self.Uploadbtn.setText(_translate("MainWindow", "Upload Photo"))
        self.groupBox.setTitle(_translate("MainWindow", "Search Window"))
        self.searchbtn.setText(_translate("MainWindow", "Search"))
        item = self.tbresult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tbresult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tbresult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tbresult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Photo"))
        self.pushButton.setText(_translate("MainWindow", "Submitt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
